#!/bin/bash
# Contract test: golden capture of the PREPARE_CMD string generated by the
# extension live sequencer (orchestration/extension/live.sh) for one fixed
# input (--start-watch, wallet fixture present, stub chrome bin).
#
# History: fixtures/prepare-cmd.golden froze the pre-decomposition
# mega-string. The sequencer now emits fixtures/prepare-cmd.sequencer.golden:
# the same operations in the same order (watch ownership -> dist snapshot ->
# fixture prefill -> detached chrome -> CDP poll -> fixture seed-cdp), with
# the inline blobs replaced by calls to the named feature scripts. The
# original golden is kept as the behavioral reference.
#
# Regenerate intentionally with: CT_GOLDEN_UPDATE=1 bash tests/contract/run.sh extension-live-prepare-cmd
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/helpers.sh"
ct_init

GOLDEN="$CT_REPO_ROOT/tests/contract/fixtures/prepare-cmd.sequencer.golden"
LIVE_SRC="$CT_REPO_ROOT/orchestration/extension/live.sh"

# Installed-style sandbox: live.sh co-located with its feature scripts and a
# stub launch.sh (records the --prepare-cmd value) + stub verify.sh.
INST="$CT_TMP/installed"
mkdir -p "$INST/lib"
cp "$LIVE_SRC" "$INST/live.sh"
cp "$CT_REPO_ROOT/orchestration/lib/harness-path.sh" "$INST/lib/"
cp "$CT_REPO_ROOT/orchestration/lib/path-defaults.json" "$INST/lib/"
cp "$CT_REPO_ROOT/orchestration/lib/json-field.sh" "$INST/lib/"
cp "$CT_REPO_ROOT/orchestration/extension/launch-browser.cjs" "$INST/"
cp "$CT_REPO_ROOT/orchestration/extension/start-watch.sh" "$INST/"
cp "$CT_REPO_ROOT/orchestration/extension/snapshot-dist.sh" "$INST/"
cp "$CT_REPO_ROOT/orchestration/extension/seed-fixture.sh" "$INST/"
cp "$CT_REPO_ROOT/recipe/extension/wallet-fixture-state.cjs" "$INST/wallet-fixture-state.cjs"
cat > "$INST/launch.sh" <<SH
#!/bin/bash
prev=""
for a in "\$@"; do
  if [ "\$prev" = "--prepare-cmd" ]; then printf '%s' "\$a" > "$CT_TMP/prepare-cmd.txt"; fi
  prev="\$a"
done
exit 0
SH
cat > "$INST/verify.sh" <<'SH'
#!/bin/bash
exit 0
SH
chmod +x "$INST"/*.sh "$INST"/*.cjs

# Fixed stub target: built dist + wallet fixture in the runtime dir
TGT="$CT_TMP/target"
ct_stub_extension_repo "$TGT"
mkdir -p "$TGT/temp/recipe/runtime"
echo '{"password":"stub-password"}' > "$TGT/temp/recipe/runtime/wallet-fixture.json"
CHROME="$(ct_stub_chrome_bin "$CT_TMP/cbin")"

ART="$CT_TMP/artifacts"
ct_run 0 timeout 60 env RECIPE_HARNESS_CHROME_BIN="$CHROME" \
  bash "$INST/live.sh" --target "$TGT" --cdp-port 9333 --start-watch --artifacts-dir "$ART"

ct_assert_file "$CT_TMP/prepare-cmd.txt"
# fixture provenance is written by seed-fixture resolve before launch
ct_assert_json_field "$ART/logs/fixture-source.json" "j.status" "present"

# Normalize the only run-variable piece (the sandbox root) so the golden is stable.
sed -e "s|$CT_TMP|__SANDBOX__|g" "$CT_TMP/prepare-cmd.txt" > "$CT_TMP/prepare-cmd.normalized"

if [ "${CT_GOLDEN_UPDATE:-}" = "1" ]; then
  mkdir -p "$(dirname "$GOLDEN")"
  cp "$CT_TMP/prepare-cmd.normalized" "$GOLDEN"
  echo "golden updated: $GOLDEN"
  exit 0
fi

ct_assert_file "$GOLDEN"
if ! diff -u "$GOLDEN" "$CT_TMP/prepare-cmd.normalized" > "$CT_TMP/golden.diff"; then
  cat "$CT_TMP/golden.diff" >&2
  ct_fail "sequencer PREPARE_CMD deviates from the golden fixture"
fi

# Equivalence with the pre-decomposition golden: same operation sequence.
OLD_GOLDEN="$CT_REPO_ROOT/tests/contract/fixtures/prepare-cmd.golden"
ct_assert_file "$OLD_GOLDEN"
for marker in "start-watch.sh" "snapshot-dist.sh" "seed-fixture.sh prefill" "launch-browser.cjs" "json/version" "seed-fixture.sh seed-cdp"; do
  ct_assert_contains "$(cat "$GOLDEN")" "$marker"
done
# operations the old golden encoded inline must now live in the extracted scripts
grep -q "recipe-harness-webpack.pid" "$OLD_GOLDEN" || ct_fail "old golden sanity"
grep -q "recipe-harness-webpack.pid" "$CT_REPO_ROOT/orchestration/extension/start-watch.sh" || ct_fail "watch ownership lost"
grep -q "exclude _metadata" "$CT_REPO_ROOT/orchestration/extension/snapshot-dist.sh" || ct_fail "snapshot rsync lost"
grep -q "from git id" "$CT_REPO_ROOT/orchestration/extension/snapshot-dist.sh" || ct_fail "freshness guard lost"
